#!/bin/bash
# Export Environment Variables for Railway Deployment
# Run this in Replit Shell to see all your secrets

echo "================================================"
echo "HYPERDAG ENVIRONMENT VARIABLES FOR RAILWAY"
echo "================================================"
echo ""
echo "Copy these values to Railway 'Variables' tab:"
echo ""

echo "# === REQUIRED VARIABLES ==="
echo "NODE_ENV=production"
echo "PORT=5000"
echo ""

echo "# === DATABASE (Railway auto-generates this) ==="
echo "# DATABASE_URL=<auto-generated-by-railway>"
echo ""

echo "# === SUPABASE ==="
if [ -n "$SUPABASE_URL" ]; then
  echo "SUPABASE_URL=$SUPABASE_URL"
else
  echo "# SUPABASE_URL=<not-set>"
fi

if [ -n "$SUPABASE_SERVICE_KEY" ]; then
  echo "SUPABASE_SERVICE_KEY=***hidden***  # Check Replit Secrets"
else
  echo "# SUPABASE_SERVICE_KEY=<not-set>"
fi
echo ""

echo "# === AI PROVIDERS ==="
if [ -n "$OPENAI_API_KEY" ]; then
  echo "OPENAI_API_KEY=***hidden***  # Check Replit Secrets"
else
  echo "# OPENAI_API_KEY=<not-set>"
fi

if [ -n "$ANTHROPIC_API_KEY" ]; then
  echo "ANTHROPIC_API_KEY=***hidden***  # Check Replit Secrets"
else
  echo "# ANTHROPIC_API_KEY=<not-set>"
fi

if [ -n "$GROQ_API_KEY" ]; then
  echo "GROQ_API_KEY=***hidden***  # Check Replit Secrets"
else
  echo "# GROQ_API_KEY=<not-set>"
fi
echo ""

echo "# === BLOCKCHAIN ==="
if [ -n "$ALCHEMY_API_KEY" ]; then
  echo "ALCHEMY_API_KEY=***hidden***  # Check Replit Secrets"
else
  echo "# ALCHEMY_API_KEY=<not-set>"
fi
echo ""

echo "# === EMAIL ==="
if [ -n "$MAILGUN_API_KEY" ]; then
  echo "MAILGUN_API_KEY=***hidden***  # Check Replit Secrets"
else
  echo "# MAILGUN_API_KEY=<not-set>"
fi

if [ -n "$MAILGUN_DOMAIN" ]; then
  echo "MAILGUN_DOMAIN=$MAILGUN_DOMAIN"
else
  echo "# MAILGUN_DOMAIN=<not-set>"
fi
echo ""

echo "================================================"
echo "NEXT STEPS:"
echo "1. Go to Railway dashboard"
echo "2. Click on your service → 'Variables' tab"
echo "3. Add each variable above"
echo "4. For ***hidden*** values, copy from Replit Secrets tab"
echo "================================================"
