-- Add rfpId column to votes table
ALTER TABLE IF EXISTS votes ADD COLUMN IF NOT EXISTS rfp_id INTEGER REFERENCES rfps(id);

-- Update rfps table with new columns
ALTER TABLE IF EXISTS rfps
  ALTER COLUMN rfi_id DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'other' NOT NULL,
  ADD COLUMN IF NOT EXISTS tags TEXT,
  ALTER COLUMN requirements DROP NOT NULL,
  ALTER COLUMN deliverables DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS funding_goal INTEGER DEFAULT 0 NOT NULL,
  ALTER COLUMN budget DROP NOT NULL,
  ALTER COLUMN timeline DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS upvotes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS downvotes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_staked INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_funded INTEGER DEFAULT 0,
  DROP COLUMN IF EXISTS expires_at,
  ADD COLUMN IF NOT EXISTS deadline TIMESTAMP;

-- Rename creator_id to submitter_id
ALTER TABLE IF EXISTS rfps RENAME COLUMN creator_id TO submitter_id;
