import { useState } from "react";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Loader2, SendIcon } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function AiAssistant() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [chatHistory, setChatHistory] = useState<Array<{type: 'user' | 'ai', content: string}>>([]);
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!question.trim()) {
      toast({
        title: "Empty question",
        description: "Please enter a question",
        variant: "destructive",
      });
      return;
    }
    
    try {
      setIsLoading(true);
      // Add user question to chat history
      setChatHistory(prev => [...prev, { type: 'user', content: question }]);
      
      const response = await apiRequest("POST", "/api/ai/ask", { question });
      const data = await response.json();
      
      if (data.success) {
        setAnswer(data.answer);
        // Add AI response to chat history
        setChatHistory(prev => [...prev, { type: 'ai', content: data.answer }]);
      } else {
        toast({
          title: "Error",
          description: data.message || "Failed to get an answer. Please try again.",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("AI Assistant error:", error);
      toast({
        title: "Error",
        description: "Could not connect to AI service. Please try again later.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
      setQuestion("");
    }
  };

  return (
    <div className="flex flex-col space-y-4">
      <Card className="p-6 bg-white shadow-md rounded-lg mb-4">
        <div className="max-h-[500px] overflow-y-auto mb-4 space-y-4">
          {chatHistory.length === 0 ? (
            <div className="text-center text-gray-500 py-12">
              <p className="text-lg">Ask the AI assistant a question about HyperDAG</p>
              <p className="text-sm mt-2">Examples:</p>
              <ul className="text-sm mt-1 space-y-1">
                <li>• What is RepID?</li>
                <li>• How does HyperCrowd work?</li>
                <li>• Tell me about Zero-Knowledge Proofs in HyperDAG</li>
              </ul>
            </div>
          ) : (
            chatHistory.map((message, index) => (
              <div 
                key={index} 
                className={`p-3 rounded-lg ${message.type === 'user' ? 'bg-blue-50 ml-12' : 'bg-gray-50 mr-12'}`}
              >
                <div className="flex items-start">
                  <div className={`flex-shrink-0 h-8 w-8 rounded-full ${message.type === 'user' ? 'bg-blue-500' : 'bg-emerald-500'} flex items-center justify-center text-white font-medium`}>
                    {message.type === 'user' ? 'U' : 'AI'}
                  </div>
                  <div className="ml-3">
                    <p className="text-gray-800 whitespace-pre-wrap">{message.content}</p>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
        
        <form onSubmit={handleSubmit} className="flex items-end space-x-2">
          <div className="flex-grow">
            <Input
              placeholder="Ask a question about HyperDAG..."
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              disabled={isLoading}
              className="w-full border-gray-300 focus:border-blue-500 focus:ring-blue-500"
            />
          </div>
          <Button 
            type="submit" 
            disabled={isLoading} 
            className="bg-primary hover:bg-primary-dark"
          >
            {isLoading ? (
              <Loader2 className="h-5 w-5 animate-spin" />
            ) : (
              <>
                <SendIcon className="h-5 w-5 mr-1" /> Ask
              </>
            )}
          </Button>
        </form>
      </Card>
      
      <div className="text-sm text-gray-500 text-center mt-2">
        <p>The AI assistant is powered by Perplexity AI and provides information about HyperDAG.</p>
        <p>Responses are generated by AI and may occasionally provide inaccurate information.</p>
      </div>
    </div>
  );
}
